### ISSUE TITLE
TypeError: a is undefined

### ISSUE THREAD

**Issue by severin-bruhat** [liangsun/meteor-ckeditor#1]
Hi, 
I'm using this package on my meteor project.
I'm having the following issue : 

TypeError: a is undefined meteor.js:888:11
a@http://cdn.ckeditor.com/4.5.2/standard/ckeditor.js:322:77
CKEDITOR.replace@http://cdn.ckeditor.com/4.5.2/standard/ckeditor.js:326:433
@http://meteor-128110.nitrousapp.com:3000/client/templates/edit_slide/edit_slide.js?e22ccfcd978a73b10aa0f815e79bd9ac658907e2:87:1
fireCallbacks/<@http://meteor-128110.nitrousapp.com:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3155:9
Template._withTemplateInstanceFunc@http://meteor-128110.nitrousapp.com:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
fireCallbacks@http://meteor-128110.nitrousapp.com:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3151:1

Any clue ?
Thanks

**Comment by 1e0ng** [comment]
Hi, would you tell me how to reproduce? Because I just created a todos example with this package, and it seems works without errors.

**Comment by severin-bruhat** [comment]
Actually, I don't know.
It's seems that it depends on the order the scripts are loaded. Sometimes it works, sometimes it doesn't

**Comment by 1e0ng** [comment]
I get it. Maybe this project is useless. You may just use code like this directly:

```
$.getScript("https://cdn.ckeditor.com/4.5.4/standard/ckeditor.js", function() {
...
})
```

and add this to `server/main.js`:

```
BrowserPolicy.content.allowOriginForAll('cdn.ckeditor.com');
```

**Comment by severin-bruhat** [comment]
I didn't make it so I have downloaded the sources instead of using a cdn and your package. Thank you for your help
